In [5]:
import pandas as pd
df= pd.read_csv("C:/Users/singh/OneDrive/Desktop/Real-Estate-Price-Prediction/data/raw/Bengaluru_House_Data.csv")

In [6]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [8]:
df.shape

(13320, 9)

In [9]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  str
 1   availability  13320 non-null  str
 2   location      13319 non-null  str
 3   size          13304 non-null  str
 4   society       7818 non-null   str
 5   total_sqft    13320 non-null  str
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), str(6)
memory usage: 936.7 KB

In [15]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [16]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(529)

In [27]:
df.head(10)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.00
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.00
8,Super built-up Area,Ready To Move,Marathahalli,3 BHK,NaN,1310,3.0,1.0,63.25
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020,6.0,NaN,370.00

In [31]:
df.sample(10)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
10891,Super built-up Area,18-May,Bharathi Nagar,2 BHK,NaN,1120,2.0,2.0,39.29
7587,Plot Area,Ready To Move,CV Raman Nagar,4 Bedroom,NaN,1100,4.0,2.0,220.00
9546,Plot Area,Ready To Move,Yemlur,5 Bedroom,Epllan,10000,5.0,NaN,1950.00
4446,Plot Area,Ready To Move,Old Town,8 Bedroom,NaN,750,8.0,NaN,200.00
4137,Super built-up Area,Ready To Move,Raja Rajeshwari Nagar,3 BHK,Dehts H,1510,2.0,3.0,59.00
6475,Super built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,GrrvaGr,1196,2.0,2.0,40.44
1479,Super built-up Area,Ready To Move,Dasarahalli,2 BHK,NaN,1300,2.0,3.0,55.00
3425,Super built-up Area,Ready To Move,Ramakrishnappa Layout,5 BHK,PeBayle,6200,5.0,NaN,720.00
12699,Super built-up Area,18-Jan,Yelahanka,1 BHK,Prensya,602,2.0,1.0,30.00
9863,Built-up Area,Ready To Move,Chikkabanavar,4 Bedroom,NaN,1500,4.0,1.0,105.00

In [33]:
df["area_type"].value_counts()

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64

In [34]:
df["size"].value_counts().head(20)

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
Name: count, dtype: int64

In [35]:
df["location"].value_counts().head(20)

location
Whitefield                  540
Sarjapur  Road              399
Electronic City             302
Kanakpura Road              273
Thanisandra                 234
Yelahanka                   213
Uttarahalli                 186
Hebbal                      177
Marathahalli                175
Raja Rajeshwari Nagar       171
Hennur Road                 152
Bannerghatta Road           152
7th Phase JP Nagar          149
Haralur Road                142
Electronic City Phase II    132
Rajaji Nagar                107
Chandapura                  100
Bellandur                    96
KR Puram                     91
Electronics City Phase 1     88
Name: count, dtype: int64

In [36]:
df["availability"].value_counts().head(20)

availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
19-Dec             185
18-Jul             143
18-Mar             131
18-Jun              99
20-Dec              98
21-Dec              93
19-Mar              88
18-Feb              62
18-Nov              47
18-Jan              43
18-Sep              41
19-Jun              40
18-Oct              39
19-Jan              39
19-Jul              36
Name: count, dtype: int64

In [37]:
df["total_sqft"].value_counts().head(20)

total_sqft
1200    843
1100    221
1500    205
2400    196
600     180
1000    172
1350    133
1050    123
1300    117
1250    114
900     112
1400    108
1800    104
1600    101
1150    101
1140     91
2000     83
1450     70
1650     69
800      67
Name: count, dtype: int64

In [39]:
df["total_sqft"].tail(20)

13300    1500
13301    1454
13302    1075
13303     774
13304    1187
13305     500
13306    1200
13307    1805
13308    1527
13309    1675
13310    1050
13311    1500
13312    1262
13313    1345
13314    1715
13315    3453
13316    3600
13317    1141
13318    4689
13319     550
Name: total_sqft, dtype: str

In [40]:
df[df["bath"]>10]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
938,Plot Area,Ready To Move,5th Phase JP Nagar,9 Bedroom,NaN,1260,11.0,NaN,290.0
1078,Plot Area,Ready To Move,BTM 1st Stage,9 Bedroom,Srvasks,3300,14.0,NaN,500.0
1718,Super built-up Area,Ready To Move,2Electronic City Phase II,27 BHK,NaN,8000,27.0,0.0,230.0
1768,Plot Area,Ready To Move,1 Ramamurthy Nagar,11 Bedroom,NaN,1200,11.0,0.0,170.0
1953,Plot Area,Ready To Move,KR Puram,8 Bedroom,NaN,1200,12.0,NaN,110.0
1979,Plot Area,Ready To Move,Hongasandra,8 Bedroom,NaN,990,12.0,0.0,120.0
3096,Super built-up Area,Ready To Move,Jp nagar 8th Phase .,10 BHK,NaN,12000,12.0,NaN,525.0
3379,Super built-up Area,Ready To Move,1Hanuman Nagar,19 BHK,NaN,2000,16.0,NaN,490.0
3609,Super built-up Area,Ready To Move,Koramangala Industrial Layout,16 BHK,NaN,10000,16.0,NaN,550.0
4684,Plot Area,Ready To Move,Munnekollal,43 Bedroom,NaN,2400,40.0,0.0,660.0
4916,Super built-up Area,Ready To Move,1Channasandra,14 BHK,NaN,1250,15.0,0.0,125.0
6937,Plot Area,Ready To Move,5th Block Hbr Layout,9 Bedroom,NaN,2600,12.0,NaN,675.0
7979,Super built-up Area,Ready To Move,1 Immadihalli,11 BHK,NaN,6000,12.0,NaN,150.0
8106,Plot Area,Ready To Move,Wilson Garden,8 Bedroom,NaN,1850,12.0,NaN,300.0
8636,Super built-up Area,Ready To Move,Neeladri Nagar,10 BHK,NaN,4000,12.0,NaN,160.0
9935,Super built-up Area,Ready To Move,1Hoysalanagar,13 BHK,NaN,5425,13.0,0.0,275.0
10695,Plot Area,18-Feb,Electronic City,9 Bedroom,NaN,1200,13.0,NaN,150.0
11128,Plot Area,Ready To Move,Jigani,10 Bedroom,NaN,1200,11.0,NaN,105.0
11559,Plot Area,18-Apr,1Kasavanhalli,18 Bedroom,HMwerCo,1200,18.0,NaN,200.0
13067,Plot Area,Ready To Move,Defence Colony,10 Bedroom,NaN,7150,13.0,NaN,3600.0

In [41]:
df[df["price"]>1000]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
408,Super built-up Area,19-Jan,Rajaji Nagar,7 BHK,NaN,12000,6.0,3.0,2200.0
605,Super built-up Area,19-Jan,Malleshwaram,7 BHK,NaN,12000,7.0,3.0,2200.0
743,Super built-up Area,Ready To Move,Cunningham Road,4 BHK,NaN,5270,4.0,3.0,1250.0
1299,Plot Area,Ready To Move,Chamrajpet,9 Bedroom,NaN,4050,7.0,1.0,1200.0
1311,Super built-up Area,Ready To Move,D Souza Layout,3 BHK,Niateki,4634,4.0,3.0,1015.0
1873,Plot Area,Ready To Move,Kasavanhalli,5 Bedroom,NaN,5800,7.0,NaN,1200.0
2286,Plot Area,Ready To Move,Kathreguppe,4 Bedroom,NaN,3200,4.0,2.0,1200.0
2623,Plot Area,18-Jul,Dodsworth Layout,4 Bedroom,NaN,30000,4.0,NaN,2100.0
3164,Plot Area,Ready To Move,Malleshwaram,4 Bedroom,NaN,5500,5.0,1.0,1500.0
3180,Super built-up Area,Ready To Move,Shanthala Nagar,5 BHK,Kierser,8321,5.0,3.0,2700.0
4162,Built-up Area,Ready To Move,Yemlur,4 Bedroom,Epllan,7000,5.0,NaN,2050.0
4929,Plot Area,18-May,Yemlur,8 Bedroom,Epllan,12000,9.0,NaN,1900.0
4963,Super built-up Area,19-Jan,Malleshwaram,5 BHK,NaN,7500,7.0,3.0,1700.0
5711,Plot Area,18-Apr,2nd Block Jayanagar,4 Bedroom,NaN,4920,5.0,2.0,1150.0
6190,Super built-up Area,18-Jan,Vasanth nagar,4 BHK,Prian E,4750,6.0,1.0,1102.0
6195,Plot Area,Ready To Move,2nd Block Hrbr Layout,3 Bedroom,NaN,4273,3.0,NaN,1100.0
6421,Plot Area,18-Sep,Bommenahalli,4 Bedroom,Prood G,2940,3.0,2.0,2250.0
6781,Built-up Area,Ready To Move,Malleshwaram,4 Bedroom,NaN,4000,4.0,2.0,1100.0
6838,Super built-up Area,19-Jan,Rajaji Nagar,5 BHK,NaN,7500,8.0,3.0,1700.0
7082,Super built-up Area,17-Sep,Ulsoor,4 BHK,NaN,7200,5.0,2.0,1584.0
7315,Plot Area,18-Apr,Yemlur,4 Bedroom,Epllan,11000,5.0,3.0,2000.0
7727,Super built-up Area,Ready To Move,Cubbon Road,4 BHK,NaN,5422,6.0,NaN,1900.0
7855,Plot Area,Ready To Move,Whitefield,4 Bedroom,Adowslm,10200,4.0,1.0,1250.0
7883,Super built-up Area,Ready To Move,Vasanth nagar,4 BHK,LeeyaCa,2000,3.0,2.0,1063.0
8165,Super built-up Area,18-May,Church Street,4 BHK,NaN,11000,4.0,1.0,1600.0
8398,Super built-up Area,Ready To Move,Bannerghatta Road,5 BHK,NaN,2500,4.0,NaN,1400.0
8546,Plot Area,Ready To Move,Dollars Colony,3 Bedroom,NaN,7800,3.0,2.0,2000.0
8592,Super built-up Area,Ready To Move,Sadashiva Nagar,4 BHK,NaN,7400,5.0,NaN,1850.0
8682,Plot Area,Ready To Move,Yemlur,4 Bedroom,Epllan,8400,5.0,2.0,1675.0
9181,Super built-up Area,19-Jan,Malleshwaram,4 BHK,NaN,6500,4.0,3.0,1400.0
9347,Plot Area,Ready To Move,Ramagondanahalli,5 Bedroom,Adion A,9600,6.0,1.0,1800.0
9439,Super built-up Area,Ready To Move,Sadashiva Nagar,5 BHK,NaN,7500,5.0,2.0,1500.0
9535,Plot Area,Ready To Move,Indira Nagar,4 Bedroom,NaN,2400,5.0,NaN,1250.0
9546,Plot Area,Ready To Move,Yemlur,5 Bedroom,Epllan,10000,5.0,NaN,1950.0
9598,Super built-up Area,19-Jan,Rajaji Nagar,4 BHK,NaN,6500,5.0,2.0,1400.0
10304,Plot Area,Ready To Move,5th Block Jayanagar,4 Bedroom,NaN,10624,4.0,2.0,2340.0
10429,Plot Area,Ready To Move,Cunningham Road,4 Bedroom,NaN,7500,6.0,2.0,1800.0
10485,Super built-up Area,18-Jul,Rajaji Nagar,5 BHK,Phaku K,7514,7.0,NaN,1500.0
11080,Super built-up Area,18-Jan,Ashok Nagar,4 BHK,NaN,8321,5.0,2.0,2912.0
11763,Plot Area,Ready To Move,Sadashiva Nagar,5 Bedroom,NaN,9600,7.0,2.0,2736.0
12443,Plot Area,Ready To Move,Dollars Colony,4 Bedroom,NaN,4350,8.0,NaN,2600.0
12987,Plot Area,Ready To Move,Dodsworth Layout,6 Bedroom,NaN,30400,4.0,2.0,1824.0
13067,Plot Area,Ready To Move,Defence Colony,10 Bedroom,NaN,7150,13.0,NaN,3600.0
13197,Plot Area,Ready To Move,Ramakrishnappa Layout,4 Bedroom,NaN,9200,4.0,NaN,2600.0
13200,Plot Area,Ready To Move,Defence Colony,6 Bedroom,NaN,8000,6.0,3.0,2800.0

In [42]:
df.duplicated().sum()

np.int64(529)

In [43]:
df_clean= df.copy()

In [44]:
df_clean=df_clean.drop_duplicates()

In [46]:
df_clean.shape

(12791, 9)

In [47]:
df_clean.duplicated().sum()

np.int64(0)

In [48]:
df_clean.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5328
total_sqft         0
bath              73
balcony          605
price              0
dtype: int64

In [49]:
df_clean["total_sqft"].unique()[:50]

<StringArray>
[       '1056',        '2600',        '1440',        '1521',        '1200',
        '1170',        '2732',        '3300',        '1310',        '1020',
        '1800',        '2785',        '1000',        '1100',        '2250',
        '1175',        '1180',        '1540',        '2770',         '600',
        '1755',        '2800',        '1767',         '510',        '1250',
         '660',        '1610',        '1151',        '1025', '2100 - 2850',
        '1075',        '1760',        '1693',        '1925',         '700',
        '1070',        '1724',        '1290',        '1143',        '1296',
        '1254',     '1330.74',         '970',        '1459',         '800',
         '869',        '1270',        '1670',        '2010',        '1185']
Length: 50, dtype: str

In [50]:
df_clean["total_sqft"].tail(50)

13263           1380
13264           1095
13265    1133 - 1384
13266           1665
13267           1245
13268           3360
13269           2010
13270           1226
13272           1226
13273            510
13275           1600
13276           1000
13277           1400
13278           1256
13279           1200
13280           1425
13281           1375
13282           1919
13283           2111
13284            970
13286           1405
13287           1285
13288           1050
13289           1349
13290           4050
13291            812
13292           1440
13293           2425
13294           2200
13295           1810
13296           1200
13297           1060
13298           1015
13300           1500
13301           1454
13302           1075
13303            774
13304           1187
13305            500
13306           1200
13307           1805
13308           1527
13309           1675
13310           1050
13312           1262
13314           1715
13315           3453
13316           3600
13317           1141
13318           4689
Name: total_sqft, dtype: str

In [51]:
df_clean[df_clean["total_sqft"].str.contains("-", na=False)]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
30,Super built-up Area,19-Dec,Yelahanka,4 BHK,LedorSa,2100 - 2850,4.0,0.0,186.000
56,Built-up Area,20-Feb,Devanahalli,4 Bedroom,BrereAt,3010 - 3410,NaN,NaN,192.000
81,Built-up Area,18-Oct,Hennur Road,4 Bedroom,Gollela,2957 - 3450,NaN,NaN,224.500
122,Super built-up Area,18-Mar,Hebbal,4 BHK,SNontle,3067 - 8156,4.0,0.0,477.000
137,Super built-up Area,19-Mar,8th Phase JP Nagar,2 BHK,Vaarech,1042 - 1105,2.0,0.0,54.005
...,...,...,...,...,...,...,...,...,...
12975,Super built-up Area,20-Aug,Whitefield,2 BHK,Bhath N,850 - 1060,2.0,0.0,38.190
12990,Super built-up Area,18-May,Talaghattapura,3 BHK,Sodgere,1804 - 2273,3.0,0.0,122.000
13059,Super built-up Area,Ready To Move,Harlur,2 BHK,Shodsir,1200 - 1470,2.0,0.0,72.760
13240,Super built-up Area,Ready To Move,Devanahalli,1 BHK,Pardsri,1020 - 1130,NaN,NaN,52.570
13265,Super built-up Area,20-Sep,Hoodi,2 BHK,Ranuetz,1133 - 1384,2.0,0.0,59.135

In [53]:
df_clean[df_clean["total_sqft"].str.contains("Sq", na=False)]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
410,Super built-up Area,Ready To Move,Kengeri,1 BHK,NaN,34.46Sq. Meter,1.0,0.0,18.50
775,Built-up Area,Ready To Move,Basavanagara,1 BHK,NaN,1000Sq. Meter,2.0,1.0,93.00
872,Super built-up Area,Ready To Move,Singapura Village,2 BHK,NaN,1100Sq. Yards,2.0,NaN,45.00
1400,Super built-up Area,Ready To Move,Chamrajpet,9 BHK,NaN,716Sq. Meter,9.0,1.0,296.00
1712,Plot Area,Ready To Move,Singena Agrahara,3 Bedroom,CoiewSy,1500Sq. Meter,3.0,1.0,95.00
1743,Super built-up Area,19-Mar,Hosa Road,3 BHK,Sosisic,142.61Sq. Meter,3.0,1.0,115.00
1821,Plot Area,Ready To Move,Sarjapur,3 Bedroom,Inensba,1574Sq. Yards,3.0,1.0,76.00
2310,Super built-up Area,Ready To Move,Whitefield,4 BHK,Haestt,361.33Sq. Yards,4.0,NaN,270.00
2881,Built-up Area,Ready To Move,Volagerekallahalli,2 BHK,PSterAs,117Sq. Yards,2.0,2.0,38.00
3228,Built-up Area,Ready To Move,Dodda Banaswadi,5 Bedroom,NaN,3040Sq. Meter,5.0,1.0,140.00
3285,Plot Area,18-May,Whitefield,4 Bedroom,Prtates,500Sq. Yards,4.0,2.0,378.00
4113,Super built-up Area,18-Jan,BTM Layout,3 BHK,NaN,167Sq. Meter,3.0,2.0,10.00
4293,Built-up Area,Ready To Move,Bannerghatta Road,4 BHK,NaN,315Sq. Yards,5.0,NaN,260.00
5537,Built-up Area,Ready To Move,Frazer Town,3 BHK,CaaveEn,188.89Sq. Yards,3.0,1.0,180.00
5631,Super built-up Area,Ready To Move,Thanisandra,3 BHK,Soitya,204Sq. Meter,4.0,2.0,185.00
5668,Built-up Area,Ready To Move,Judicial Layout,5 Bedroom,NaN,45Sq. Yards,6.0,3.0,400.00
5708,Plot Area,Ready To Move,Jigani,4 Bedroom,Ceeury,133.3Sq. Yards,3.0,2.0,160.00
5976,Built-up Area,Ready To Move,1st Phase JP Nagar,1 BHK,Opamaan,78.03Sq. Meter,1.0,1.0,63.00
6268,Built-up Area,Ready To Move,Chickpet,2 BHK,NaN,122Sq. Yards,2.0,0.0,48.00
6303,Built-up Area,Ready To Move,JP Nagar,3 BHK,NaN,84.53Sq. Meter,3.0,1.0,69.34
6592,Built-up Area,Ready To Move,Langford Town,4 BHK,NaN,697Sq. Meter,4.0,2.0,211.00
6953,Super built-up Area,18-Aug,Hosa Road,3 BHK,Sosisic,142.61Sq. Meter,3.0,1.0,109.00
7248,Built-up Area,Ready To Move,Hulimavu,2 BHK,NaN,132Sq. Yards,2.0,3.0,46.00
7520,Super built-up Area,Ready To Move,Doddaballapur,3 BHK,NaN,1100Sq. Meter,2.0,1.0,48.00
8273,Built-up Area,Ready To Move,V.V Puram,3 BHK,NaN,151.11Sq. Yards,2.0,0.0,150.00
9519,Built-up Area,Ready To Move,Bommenahalli,3 Bedroom,Prood G,2940Sq. Yards,3.0,1.0,232.00
9734,Carpet Area,Ready To Move,Yelahanka New Town,1 BHK,KHatsFl,45.06Sq. Meter,2.0,1.0,18.00
10491,Super built-up Area,Ready To Move,Rajapura,2 BHK,NaN,86.72Sq. Meter,2.0,2.0,40.00
12186,Built-up Area,Ready To Move,7th Phase JP Nagar,2 BHK,NaN,120Sq. Yards,2.0,1.0,51.00
12252,Built-up Area,Ready To Move,Gowdanapalya,5 BHK,NaN,24Sq. Meter,5.0,0.0,75.00
12560,Super built-up Area,18-Dec,Hosa Road,3 BHK,Sosisic,142.84Sq. Meter,3.0,1.0,110.00
12652,Plot Area,Ready To Move,Billamaranahalli,2 Bedroom,AWharan,300Sq. Yards,2.0,2.0,150.00

In [54]:
df_clean["size"].unique()

<StringArray>
[     '2 BHK',  '4 Bedroom',      '3 BHK',      '4 BHK',  '6 Bedroom',
  '3 Bedroom',      '1 BHK',       '1 RK',  '1 Bedroom',  '8 Bedroom',
  '2 Bedroom',  '7 Bedroom',      '5 BHK',      '7 BHK',      '6 BHK',
  '5 Bedroom',     '11 BHK',      '9 BHK',          nan,  '9 Bedroom',
     '27 BHK', '10 Bedroom', '11 Bedroom',     '10 BHK',     '19 BHK',
     '16 BHK', '43 Bedroom',     '14 BHK',      '8 BHK', '12 Bedroom',
     '13 BHK', '18 Bedroom']
Length: 32, dtype: str

In [56]:
df_clean["size"].value_counts().tail(20)

size
7 Bedroom     82
5 BHK         59
9 Bedroom     46
6 BHK         30
7 BHK         17
1 RK          13
10 Bedroom    12
9 BHK          8
8 BHK          5
11 BHK         2
11 Bedroom     2
10 BHK         2
27 BHK         1
19 BHK         1
16 BHK         1
43 Bedroom     1
14 BHK         1
12 Bedroom     1
13 BHK         1
18 Bedroom     1
Name: count, dtype: int64

In [57]:
df_clean["bhk"] = df_clean["size"].str.extract(r"(\d+)").astype(float)

In [58]:
df_clean[["size", "bhk"]].head(20)

         size  bhk
0       2 BHK  2.0
1   4 Bedroom  4.0
2       3 BHK  3.0
3       3 BHK  3.0
4       2 BHK  2.0
5       2 BHK  2.0
6       4 BHK  4.0
7       4 BHK  4.0
8       3 BHK  3.0
9   6 Bedroom  6.0
10      3 BHK  3.0
11  4 Bedroom  4.0
12      2 BHK  2.0
13      2 BHK  2.0
14  3 Bedroom  3.0
15      2 BHK  2.0
16      3 BHK  3.0
17      3 BHK  3.0
18      3 BHK  3.0
19      2 BHK  2.0

In [59]:
df_clean["bhk"].value_counts().sort_index()

bhk
1.0      638
2.0     5245
3.0     4655
4.0     1398
5.0      350
6.0      221
7.0       99
8.0       89
9.0       54
10.0      14
11.0       4
12.0       1
13.0       1
14.0       1
16.0       1
18.0       1
19.0       1
27.0       1
43.0       1
Name: count, dtype: int64

In [61]:
def convert_sqft(value):
    value=str(value).strip()
    #handle ranges  
    if "-" in value:
        parts=value.split("-")
        try:
            low=float(parts[0])
            high = float(parts[1])
            return (low+high)/2
        except:
            return None
    #sqaure meter
    if "Sq. Meter" in value:
        try:
            number = float(value.replace("Sq. Meter","").strip())
            return number * 10.7639
        except:
            return None

    #Square yard
    if "Sq. Yards" in value:
        try:
            number = float(value.replace("Sq. Yards", "").strip())
            return number * 9
        except:
            return None

    # Perch
    if "Perch" in value:
        try:
            number = float(value.replace("Perch", "").strip())
            return number * 272.25
        except:
            return None

    # Guntha
    if "Guntha" in value:
        try:
            number = float(value.replace("Guntha", "").strip())
            return number * 1089
        except:
            return None

    # Acre
    if "Acres" in value:
        try:
            number = float(value.replace("Acres", "").strip())
            return number * 43560
        except:
            return None

    # Cent
    if "Cents" in value:
        try:
            number = float(value.replace("Cents", "").strip())
            return number * 435.6
        except:
            return None

    # Ground
    if "Grounds" in value:
        try:
            number = float(value.replace("Grounds", "").strip())
            return number * 2400
        except:
            return None

    # Normal numeric value
    try:
        return float(value)
    except:
        return None

In [62]:
df_clean["total_sqft_clean"] = df_clean["total_sqft"].apply(convert_sqft)

In [63]:
df_clean[["total_sqft", "total_sqft_clean"]].head(20)

   total_sqft  total_sqft_clean
0        1056            1056.0
1        2600            2600.0
2        1440            1440.0
3        1521            1521.0
4        1200            1200.0
5        1170            1170.0
6        2732            2732.0
7        3300            3300.0
8        1310            1310.0
9        1020            1020.0
10       1800            1800.0
11       2785            2785.0
12       1000            1000.0
13       1100            1100.0
14       2250            2250.0
15       1175            1175.0
16       1180            1180.0
17       1540            1540.0
18       2770            2770.0
19       1100            1100.0

In [64]:
df_clean["total_sqft_clean"].isnull().sum()

np.int64(0)

In [65]:
df_clean=df_clean.rename(columns={
    "total_sqft_clean":"total_sqft_num"
})

In [66]:
df_clean[[
    "location",
    "size",
    "availability",
    "bhk",
    "location",
    "total_sqft",
    "total_sqft_num",
    "bath",
    "balcony",
    "price"
]].head(20)

,location,size,availability,bhk,location,total_sqft,total_sqft_num,bath,balcony,price
0,Electronic City Phase II,2 BHK,19-Dec,2.0,Electronic City Phase II,1056,1056.0,2.0,1.0,39.07
1,Chikka Tirupathi,4 Bedroom,Ready To Move,4.0,Chikka Tirupathi,2600,2600.0,5.0,3.0,120.00
2,Uttarahalli,3 BHK,Ready To Move,3.0,Uttarahalli,1440,1440.0,2.0,3.0,62.00
3,Lingadheeranahalli,3 BHK,Ready To Move,3.0,Lingadheeranahalli,1521,1521.0,3.0,1.0,95.00
4,Kothanur,2 BHK,Ready To Move,2.0,Kothanur,1200,1200.0,2.0,1.0,51.00
5,Whitefield,2 BHK,Ready To Move,2.0,Whitefield,1170,1170.0,2.0,1.0,38.00
6,Old Airport Road,4 BHK,18-May,4.0,Old Airport Road,2732,2732.0,4.0,NaN,204.00
7,Rajaji Nagar,4 BHK,Ready To Move,4.0,Rajaji Nagar,3300,3300.0,4.0,NaN,600.00
8,Marathahalli,3 BHK,Ready To Move,3.0,Marathahalli,1310,1310.0,3.0,1.0,63.25
9,Gandhi Bazar,6 Bedroom,Ready To Move,6.0,Gandhi Bazar,1020,1020.0,6.0,NaN,370.00
10,Whitefield,3 BHK,18-Feb,3.0,Whitefield,1800,1800.0,2.0,2.0,70.00
11,Whitefield,4 Bedroom,Ready To Move,4.0,Whitefield,2785,2785.0,5.0,3.0,295.00
12,7th Phase JP Nagar,2 BHK,Ready To Move,2.0,7th Phase JP Nagar,1000,1000.0,2.0,1.0,38.00
13,Gottigere,2 BHK,Ready To Move,2.0,Gottigere,1100,1100.0,2.0,2.0,40.00
14,Sarjapur,3 Bedroom,Ready To Move,3.0,Sarjapur,2250,2250.0,3.0,2.0,148.00
15,Mysore Road,2 BHK,Ready To Move,2.0,Mysore Road,1175,1175.0,2.0,2.0,73.50
16,Bisuvanahalli,3 BHK,Ready To Move,3.0,Bisuvanahalli,1180,1180.0,3.0,2.0,48.00
17,Raja Rajeshwari Nagar,3 BHK,Ready To Move,3.0,Raja Rajeshwari Nagar,1540,1540.0,3.0,3.0,60.00
18,Ramakrishnappa Layout,3 BHK,Ready To Move,3.0,Ramakrishnappa Layout,2770,2770.0,4.0,2.0,290.00
19,Manayata Tech Park,2 BHK,Ready To Move,2.0,Manayata Tech Park,1100,1100.0,2.0,2.0,48.00

In [67]:
df_clean=df_clean.dropna(subset=["location","size"])

In [68]:
df_clean.shape

(12774, 11)

In [69]:
df_clean=df_clean.drop(columns=["society"])

In [70]:
df_clean.columns

Index(['area_type', 'availability', 'location', 'size', 'total_sqft', 'bath',
       'balcony', 'price', 'bhk', 'total_sqft_num'],
      dtype='str')

In [71]:
df_clean.isnull().sum()

area_type           0
availability        0
location            0
size                0
total_sqft          0
bath               57
balcony           589
price               0
bhk                 0
total_sqft_num      0
dtype: int64

In [72]:
df_clean[df_clean["total_sqft_num"].isnull()][
    ["location", "size", "bhk", "total_sqft", "price"]
]

Empty DataFrame
Columns: [location, size, bhk, total_sqft, price]
Index: []

In [74]:
df_clean["total_sqft_num"].isnull().sum()

np.int64(0)

In [76]:
df_clean.shape
df_clean.isnull().sum()

area_type           0
availability        0
location            0
size                0
total_sqft          0
bath               57
balcony           589
price               0
bhk                 0
total_sqft_num      0
dtype: int64

In [77]:
df_clean["bath"]=df_clean.groupby("bhk")["bath"].transform(
    lambda x:x.fillna(x.median())
)

In [78]:
df_clean["bath"].isnull().sum()

np.int64(0)

In [79]:
df_clean["balcony"]=df_clean["balcony"].fillna(
    df_clean["balcony"].median()
)

In [80]:
df_clean["balcony"].isnull().sum()

np.int64(0)

In [81]:
df_clean.isnull().sum()

area_type         0
availability      0
location          0
size              0
total_sqft        0
bath              0
balcony           0
price             0
bhk               0
total_sqft_num    0
dtype: int64

In [82]:
df_clean.shape

(12774, 10)

In [85]:
df_clean.to_csv(
   "C:/Users/singh/OneDrive/Desktop/Real-Estate-Price-Prediction/data/processed/house_prices_cleaned.csv",
    index=False
)